src/apps/weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DashboardView.as_view(), name='index'),
    path('list', views.WeatherListView.as_view(), name='list'),
    path('add-city', views.AddNewRegionView.as_view(), name='add_city'),
]

src/meteorology/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.weather.urls')),
]

src/apps/queues/models.py
from django.db import models
from django.db.models.signals import post_save
import uuid
from .scheduler import JobController


class Job(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    error = models.TextField(blank=True)

    def __str__(self):
        return f"Job-ID: {self.id}"


def post_save_run_job(sender, instance, created, *args, **kwargs):
    if created:
        task = JobController()
        task.job_weather_create()
post_save.connect(post_save_run_job, sender=Job)

src/apps/weather/models.py
# API KEY dca5866c7ce15e293544c5154fc22dc6
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


class City(TimestampedModel):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Cities'


class Forecast(TimestampedModel):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    temperature = models.DecimalField(default=0.00, max_digits=5, decimal_places=2)
    description = models.CharField(max_length=256, blank=True)
    icon = models.CharField(max_length=64, blank=True)

    class TemperatureType(models.IntegerChoices):
        C = 1, "C"
        F = 2, "F"

    type = models.PositiveSmallIntegerField(choices=TemperatureType.choices, default=TemperatureType.C)

    def __str__(self):
        return f"{self.city.name} / {self.temperature}"

    class Meta:
        verbose_name_plural = 'Forecast'

src/apps/weather/forms.py
from django.forms import ModelForm, TextInput
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name' : TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'})}

src/apps/queues/views.py
from django.shortcuts import render

# Create your views here.

src/apps/weather/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView
from .models import City, Forecast
from .utils import WeatherController
from .forms import CityForm


class DashboardView(View):
    template_name = 'index.html'

    def get(self, request):
        # return render(request, self.template_name)
        return redirect('list')


class AddNewRegionView(View, WeatherController):
    template_name = 'weather/add-region.html'
    form = CityForm

    def get(self, request):
        context = {'form': self.form(), 'is_added': False}
        return render(request, 'weather/add-region.html', context)

    def post(self, request):
        city_name = request.POST['name']
        qs = City.objects.filter(name__icontains=city_name)
        if qs.exists():
            city = qs.first()
            form = self.form(request.POST)
        else:
            form = self.form(request.POST)
            city = form.save()
        city_weather = self.fetch_one(city=city)
        context = {'city_weather': city_weather, 'form': form, 'is_added': True}
        return render(request, 'weather/add-region.html', context)


class WeatherListView(ListView):
    template_name = 'weather/list.html'
    queryset = Forecast.objects.all()
    context_object_name = 'object_list'

    def get_queryset(self):
        query = self.request.GET.get('name', None)
        qs = Forecast.objects.all()
        if query:
            qs = qs.filter(city__name__icontains=query)
        return qs

src/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>The weather</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css"/>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Amarante');

        html {
            overflow-y: scroll;
        }

        ::selection {
            background: #5f74a0;
            color: #fff;
        }

        ::-moz-selection {
            background: #5f74a0;
            color: #fff;
        }

        ::-webkit-selection {
            background: #5f74a0;
            color: #fff;
        }

        br {
            display: block;
            line-height: 1.6em;
        }

        article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
            display: block;
        }

        ol, ul {
            list-style: none;
        }

        input, textarea {
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            outline: none;
        }

        blockquote, q {
            quotes: none;
        }

        strong, b {
            font-weight: bold;
        }

        table {
            border: 1px solid #e8e8e8;
            border-collapse: collapse;
            border-spacing: 0;
        }

        img {
            border: 0;
            max-width: 100%;
        }

        h1 {
            font-family: 'Amarante', Tahoma, sans-serif;
            font-weight: bold;
            font-size: 3.6em;
            line-height: 1.7em;
            margin-bottom: 10px;
            text-align: center;
        }


        /** page structure **/
        #wrapper {
            display: block;
            width: 850px;
            background: #fff;
            margin: 0 auto;
            padding: 10px 17px;
            -webkit-box-shadow: 2px 2px 3px -1px rgba(0, 0, 0, 0.35);
        }

        #keywords {
            margin: 0 auto;
            font-size: 1.2em;
            margin-bottom: 15px;
        }


        #keywords thead {
            cursor: pointer;
            background: #209cee14;
        }

        #keywords thead tr th {
            font-weight: bold;
            padding: 12px 30px;
            padding-left: 42px;
        }

        #keywords thead tr th span {
            padding-right: 20px;
            background-repeat: no-repeat;
            background-position: 100% 100%;
        }

        #keywords thead tr th.headerSortUp, #keywords thead tr th.headerSortDown {
            background: #acc8dd;
        }

        #keywords thead tr th.headerSortUp span {
            background-image: url('https://i.imgur.com/SP99ZPJ.png');
        }

        #keywords thead tr th.headerSortDown span {
            background-image: url('https://i.imgur.com/RkA9MBo.png');
        }


        #keywords tbody tr {
            color: #555;
        }

        #keywords tbody tr td {
            text-align: center;
            padding: 15px 10px;
        }

        #keywords tbody tr td.lalign {
            text-align: left;
        }
    </style>
</head>

<body>
<section class="" style="background: #e99c4c">
    <div class="">
        <div class="container" style="display: flex;">
            <div>
                <img src="https://openweathermap.org/img/wn/02d@2x.png" alt="Mete">
            </div>
            <a href="{% url 'index' %}">
                <h1 style="margin-top: 25px;font-size: 40px;color: white;">The weather</h1>
            </a>
            <div style="display: flex;margin: 52px 0 0 13px;color: bisque;padding: 0;">
                <a href="{% url 'list' %}" style="color: white">
                    <h5 style="margin: 0 10px 0 10px;">Analytics</h5>
                </a>
                <a href="{% url 'add_city' %}" style="color: white">
                    <h5 style="margin-left: 10px">Add city</h5>
                </a>
            </div>
        </div>
    </div>
</section>
{% block content %}
{% endblock %}

</body>
</html>

src/templates/weather/add-region.html
{% extends 'index.html' %}

{% block content %}
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                {{ form.name }}
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% if is_added %}
                        <div class="box" style="box-shadow: 5px 5px 15px 5px #dadee3;">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="https://openweathermap.org/img/w/{{ city_weather.icon }}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{ city_weather.city }}</span>
                                        <br>
                                        <span class="subtitle">{{ city_weather.temperature }}° C</span>
                                        <br> {{ city_weather.description }}
                                    </p>
                                </div>
                            </div>
                        </article>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/weather/list.html
{% extends 'index.html' %}

{% block content %}
    <section style="padding-top: 50px">
        <div class="container">
            <div class="columns" style="display: flex;justify-content: end;width: 89%;">
                <div>
                    <form method="GET" action="{% url 'list' %}">
                        <div class="field has-addons">
                            <div class="control is-expanded">
                                <label for="id_name"></label>
                                <input type="text" name="name" class="input" placeholder="City name" maxlength="25" required="" id="id_name">
                            </div>
                            <div class="control">
                                <button type="submit" class="button is-info">Search</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div></div>

        </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <table id="keywords">
                        <thead>
                        <tr>
                            <th>City</th>
                            <th>Temperature</th>
                            <th>Type</th>
                            <th>Description</th>
                            <th>Icon</th>
                            <th>Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in object_list %}
                            <tr style="font-size: 16px">
                                <td style="text-align: left; padding: 16px;">{{ item.city.name }}</td>
                                <td>{{ item.temperature }}</td>
                                <td>° {{ item.get_type_display }}</td>
                                <td>{{ item.description }}</td>
                                <td style="padding: 0">
                                    <img style="width: 45%" src="https://openweathermap.org/img/w/{{ item.icon }}.png"
                                         alt="Image">
                                </td>
                                <td>{{ item.created_at }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>


{% endblock %}